

stages: 
  - build
  - test
  
 
build:
    stage: build
    script:
        - apt-get update
        - mvn compile       
   

test:
    stage: test
    script:
        - mvn clean install
    






