before_script:
  - apt-get update
  - apt install -y maven

stages: 
  - build
  - test
  
 
build:
    stage: build
    script:
        - mvn compile       
   

test:
    stage: test
    script:
        - mvn clean install
    






