image: maven:3.3.9-jdk-8

stages: 
  - build
  - test
  
 
build:
    stage: build
    script:
        - mvn compile       
    tags:
        - cyclos
    

test:
    stage: test
    script:
        - mvn clean install
    tags:
        - cyclos







