before_script:
       - SET SH_HOME=C:\cygwin64
       - SET M2_HOME="C:\Program Files (x86)\apache-maven-3.6.3"
       - SET M2=%M2_HOME%\bin
       - SET path=%path%;%M2%
       - SET JAVA_HOME=C:\Program Files (x86)\Java\jdk-14.0.2\jdk-14.0.2


stages:
  - test


test:
    script:
       - 'mvn clean install'
    artifacts:
      when: always
      paths:
        - Result/
        - target/
      reports:
        junit:
          - target/surefire-reports/TEST-*.xml
          - target/failsafe-reports/TEST-*.xml
    tags:
        - test
  

    






