stages:
  - deploy
  - deploy_staging

  



deploy:
    stage: deploy
    script:
        - call ./bin/shutdown.bat
        - call ./bin/startup.bat       
    tags:
        - cyclos



deploy_staging:
  stage: deploy_staging
  script:
    - echo "Deploy"
  environment:
    name: tomcat_deploy_cyclos
    url: http://localhost:8089/cyclos
  only:
    - master
  tags:
      - cyclos







