/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-01 06:12:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.6.RELEASE.jar", Long.valueOf(1591007906000L));
    _jspx_dependants.put("jar:file:/C:/Users/user-pc/Downloads/apache-tomcat-8.5.57/webapps/cyclos/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1591007906000L));
    _jspx_dependants.put("jar:file:/C:/Users/user-pc/Downloads/apache-tomcat-8.5.57/webapps/cyclos/WEB-INF/lib/spring-webmvc-5.2.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1588041852000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.release();
    _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html language=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.builtinLanguage.isoLanguage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("    <head>\n");
      out.write("        <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.applicationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        <meta name=\"owner\" content=\"");
      if (_jspx_meth_spring_005fescapeBody_005f1(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("        <meta name=\"copyright\" content=\"");
      if (_jspx_meth_spring_005fescapeBody_005f2(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        \n");
      out.write("        <link id=\"shortcutIconLink\" rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.shortcutIconUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "basicStyle.html", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "root-path.jsp", out, false);
      out.write("\n");
      out.write("        <script>\n");
      out.write("            var cyclosVersion = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cyclosVersion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var configurationId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.configurationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";            \n");
      out.write("            var languageId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.languageId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var languageLastModified = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.languageLastModified}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var themeId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.themeId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var themeLastModified = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.themeLastModified}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var pushNotificationsClientId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pushNotificationsClientId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var countries = \"");
      if (_jspx_meth_spring_005fescapeBody_005f3(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("            var resourceCacheKey = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resourceCacheKey}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("            // IE < 10 doesn't support native Base64 methods\n");
      out.write("            if (typeof(window.atob) === \"undefined\") {\n");
      out.write("                var sc = document.createElement(\"script\");\n");
      out.write("                sc.src = rootPath + \"/js/base64.js\";\n");
      out.write("                sc.onload = function() {\n");
      out.write("                    window.btoa = Base64.encode;\n");
      out.write("                    window.atob = Base64.decode;\n");
      out.write("                }                \n");
      out.write("                document.head.appendChild(sc);\n");
      out.write("            }\n");
      out.write("            // IE doesn't support EventSource\n");
      out.write("            if (typeof(window.EventSource) === \"undefined\") {\n");
      out.write("                var sc = document.createElement(\"script\");\n");
      out.write("                sc.src = rootPath + \"/js/eventsource.js\";\n");
      out.write("                document.head.appendChild(sc);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            includeScript(\"/js/script.min.js\");\n");
      out.write("        </script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/3.0.0/load-image.all.min.js\"\n");
      out.write("            defer=\"defer\" async=\"true\"\n");
      out.write("            integrity=\"sha256-Gl9SC24yrH0WrCfsw1J+HxkemV99+AoAkxOVs3fhtHo=\"\n");
      out.write("            crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@zxing/library@0.15.2/umd/index.min.js\"\n");
      out.write("            defer=\"defer\" async=\"true\"\n");
      out.write("            integrity=\"sha256-5neFo09S0iIU7M0PNa1w/jaxskTtpCb8zdmlFaw5t9M=\"\n");
      out.write("            crossorigin=\"anonymous\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"main\">\n");
      out.write("        <iframe src=\"javascript:''\" id=\"__gwt_historyFrame\" style=\"width:0;height:0;border:0;position:absolute;\"></iframe>\n");
      out.write("        <div id=\"loadingContainer\">\n");
      out.write("            <div class=\"loadingContainerWrapper\"> \n");
      out.write("                <div id=\"problemsLoading\" style=\"display:none\"><div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${problemsLoading}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div></div>\n");
      out.write("\t\t\t\t<div class=\"loadingContainerText\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loadingApplication}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t<div id=\"loadingContainerBoxes\">\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-highlight\"></div>\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-normal\"></div>\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-normal\"></div>\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-normal\"></div>\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-normal\"></div>\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-normal\"></div>\n");
      out.write("\t\t\t\t    <div class=\"loadingContainerBox-normal\"></div>\n");
      out.write("                </div>\n");
      out.write("            </div>    \n");
      out.write("        </div>\n");
      out.write("        ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        <script>\n");
      out.write("            if (cssua.ua.ie >= 8.0 || cssua.ua.webkit || cssua.ua.firefox >= 10.0) {\n");
      out.write("                startLoading();\n");
      out.write("                includeScript(\"/cyclos.gwt/cyclos.gwt.nocache.js\", true);\n");
      out.write("            } else {\n");
      out.write("                document.body.innerHTML = \"<div id='browserNotSupported'><div id='browserNotSupportedFrame'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${browserNotSupportedJS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div></div>\";\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("        <noscript>\n");
      out.write("            <div id='browserNotSupported'><div id='browserNotSupportedFrame'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${browserNotSupported}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div></div>\n");
      out.write("        </noscript>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/pages/index.jsp(9,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty initializationData.applicationDescription}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("           <meta name=\"description\" content=\"");
          if (_jspx_meth_spring_005fescapeBody_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\">\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fescapeBody_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:escapeBody
    org.springframework.web.servlet.tags.EscapeBodyTag _jspx_th_spring_005fescapeBody_005f0 = (org.springframework.web.servlet.tags.EscapeBodyTag) _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.get(org.springframework.web.servlet.tags.EscapeBodyTag.class);
    boolean _jspx_th_spring_005fescapeBody_005f0_reused = false;
    try {
      _jspx_th_spring_005fescapeBody_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fescapeBody_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/pages/index.jsp(10,45) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fescapeBody_005f0.setHtmlEscape(true);
      int[] _jspx_push_body_count_spring_005fescapeBody_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fescapeBody_005f0 = _jspx_th_spring_005fescapeBody_005f0.doStartTag();
        if (_jspx_eval_spring_005fescapeBody_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_spring_005fescapeBody_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_spring_005fescapeBody_005f0[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005fescapeBody_005f0);
          }
          do {
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${initializationData.applicationDescription}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            int evalDoAfterBody = _jspx_th_spring_005fescapeBody_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_spring_005fescapeBody_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_spring_005fescapeBody_005f0[0]--;
          }
        }
        if (_jspx_th_spring_005fescapeBody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fescapeBody_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fescapeBody_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fescapeBody_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.reuse(_jspx_th_spring_005fescapeBody_005f0);
      _jspx_th_spring_005fescapeBody_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fescapeBody_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fescapeBody_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fescapeBody_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:escapeBody
    org.springframework.web.servlet.tags.EscapeBodyTag _jspx_th_spring_005fescapeBody_005f1 = (org.springframework.web.servlet.tags.EscapeBodyTag) _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.get(org.springframework.web.servlet.tags.EscapeBodyTag.class);
    boolean _jspx_th_spring_005fescapeBody_005f1_reused = false;
    try {
      _jspx_th_spring_005fescapeBody_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fescapeBody_005f1.setParent(null);
      // /WEB-INF/pages/index.jsp(13,36) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fescapeBody_005f1.setHtmlEscape(true);
      int[] _jspx_push_body_count_spring_005fescapeBody_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fescapeBody_005f1 = _jspx_th_spring_005fescapeBody_005f1.doStartTag();
        if (_jspx_eval_spring_005fescapeBody_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_spring_005fescapeBody_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_spring_005fescapeBody_005f1[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005fescapeBody_005f1);
          }
          do {
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${license.organizationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            int evalDoAfterBody = _jspx_th_spring_005fescapeBody_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_spring_005fescapeBody_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_spring_005fescapeBody_005f1[0]--;
          }
        }
        if (_jspx_th_spring_005fescapeBody_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fescapeBody_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fescapeBody_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fescapeBody_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.reuse(_jspx_th_spring_005fescapeBody_005f1);
      _jspx_th_spring_005fescapeBody_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fescapeBody_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fescapeBody_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fescapeBody_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:escapeBody
    org.springframework.web.servlet.tags.EscapeBodyTag _jspx_th_spring_005fescapeBody_005f2 = (org.springframework.web.servlet.tags.EscapeBodyTag) _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.get(org.springframework.web.servlet.tags.EscapeBodyTag.class);
    boolean _jspx_th_spring_005fescapeBody_005f2_reused = false;
    try {
      _jspx_th_spring_005fescapeBody_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fescapeBody_005f2.setParent(null);
      // /WEB-INF/pages/index.jsp(14,40) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fescapeBody_005f2.setHtmlEscape(true);
      int[] _jspx_push_body_count_spring_005fescapeBody_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fescapeBody_005f2 = _jspx_th_spring_005fescapeBody_005f2.doStartTag();
        if (_jspx_eval_spring_005fescapeBody_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_spring_005fescapeBody_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_spring_005fescapeBody_005f2[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005fescapeBody_005f2);
          }
          do {
            out.write("Runs on Cyclos ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cyclosVersion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" (revision ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cyclosCommitId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(") registered with key ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${license.licenseKey}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            int evalDoAfterBody = _jspx_th_spring_005fescapeBody_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_spring_005fescapeBody_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_spring_005fescapeBody_005f2[0]--;
          }
        }
        if (_jspx_th_spring_005fescapeBody_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fescapeBody_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fescapeBody_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fescapeBody_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fhtmlEscape.reuse(_jspx_th_spring_005fescapeBody_005f2);
      _jspx_th_spring_005fescapeBody_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fescapeBody_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fescapeBody_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fescapeBody_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:escapeBody
    org.springframework.web.servlet.tags.EscapeBodyTag _jspx_th_spring_005fescapeBody_005f3 = (org.springframework.web.servlet.tags.EscapeBodyTag) _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.get(org.springframework.web.servlet.tags.EscapeBodyTag.class);
    boolean _jspx_th_spring_005fescapeBody_005f3_reused = false;
    try {
      _jspx_th_spring_005fescapeBody_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fescapeBody_005f3.setParent(null);
      // /WEB-INF/pages/index.jsp(28,29) name = javaScriptEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fescapeBody_005f3.setJavaScriptEscape(true);
      int[] _jspx_push_body_count_spring_005fescapeBody_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fescapeBody_005f3 = _jspx_th_spring_005fescapeBody_005f3.doStartTag();
        if (_jspx_eval_spring_005fescapeBody_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_spring_005fescapeBody_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_spring_005fescapeBody_005f3[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005fescapeBody_005f3);
          }
          do {
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countries}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            int evalDoAfterBody = _jspx_th_spring_005fescapeBody_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_spring_005fescapeBody_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_spring_005fescapeBody_005f3[0]--;
          }
        }
        if (_jspx_th_spring_005fescapeBody_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fescapeBody_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fescapeBody_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fescapeBody_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.reuse(_jspx_th_spring_005fescapeBody_005f3);
      _jspx_th_spring_005fescapeBody_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fescapeBody_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fescapeBody_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/pages/index.jsp(30,22) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty notificationMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                ");
          if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("                var notificationLevel = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notificationLevel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\n");
          out.write("                var notificationMessage = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notificationMessageJS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\n");
          out.write("                var notificationOnly = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notificationOnly}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\";\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/pages/index.jsp(31,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("notificationMessageJS");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
        }
        do {
          if (_jspx_meth_spring_005fescapeBody_005f4(_jspx_th_c_005fset_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fescapeBody_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:escapeBody
    org.springframework.web.servlet.tags.EscapeBodyTag _jspx_th_spring_005fescapeBody_005f4 = (org.springframework.web.servlet.tags.EscapeBodyTag) _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.get(org.springframework.web.servlet.tags.EscapeBodyTag.class);
    boolean _jspx_th_spring_005fescapeBody_005f4_reused = false;
    try {
      _jspx_th_spring_005fescapeBody_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fescapeBody_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f0);
      // /WEB-INF/pages/index.jsp(31,51) name = javaScriptEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fescapeBody_005f4.setJavaScriptEscape(true);
      int[] _jspx_push_body_count_spring_005fescapeBody_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fescapeBody_005f4 = _jspx_th_spring_005fescapeBody_005f4.doStartTag();
        if (_jspx_eval_spring_005fescapeBody_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_spring_005fescapeBody_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_spring_005fescapeBody_005f4[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005fescapeBody_005f4);
          }
          do {
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notificationMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            int evalDoAfterBody = _jspx_th_spring_005fescapeBody_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_spring_005fescapeBody_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_spring_005fescapeBody_005f4[0]--;
          }
        }
        if (_jspx_th_spring_005fescapeBody_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fescapeBody_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fescapeBody_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fescapeBody_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.reuse(_jspx_th_spring_005fescapeBody_005f4);
      _jspx_th_spring_005fescapeBody_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fescapeBody_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005fescapeBody_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                var notificationLevel = null;\n");
          out.write("                var notificationMessage = null;\n");
          out.write("                var notificationOnly = false; \n");
          out.write("                if (localStorage) {\n");
          out.write("                \tnotificationLevel = localStorage.notificationLevel;\n");
          out.write("                \tnotificationMessage = localStorage.notificationMessage;\n");
          out.write("                \tdelete localStorage.notificationLevel;\n");
          out.write("                \tdelete localStorage.notificationMessage;\n");
          out.write("                }\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/pages/index.jsp(105,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("browserNotSupportedJS");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f1);
        }
        do {
          if (_jspx_meth_spring_005fescapeBody_005f5(_jspx_th_c_005fset_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fescapeBody_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:escapeBody
    org.springframework.web.servlet.tags.EscapeBodyTag _jspx_th_spring_005fescapeBody_005f5 = (org.springframework.web.servlet.tags.EscapeBodyTag) _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.get(org.springframework.web.servlet.tags.EscapeBodyTag.class);
    boolean _jspx_th_spring_005fescapeBody_005f5_reused = false;
    try {
      _jspx_th_spring_005fescapeBody_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fescapeBody_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f1);
      // /WEB-INF/pages/index.jsp(105,43) name = javaScriptEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fescapeBody_005f5.setJavaScriptEscape(true);
      int[] _jspx_push_body_count_spring_005fescapeBody_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fescapeBody_005f5 = _jspx_th_spring_005fescapeBody_005f5.doStartTag();
        if (_jspx_eval_spring_005fescapeBody_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_spring_005fescapeBody_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            _jspx_push_body_count_spring_005fescapeBody_005f5[0]++;
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_spring_005fescapeBody_005f5);
          }
          do {
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${browserNotSupported}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            int evalDoAfterBody = _jspx_th_spring_005fescapeBody_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_spring_005fescapeBody_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_spring_005fescapeBody_005f5[0]--;
          }
        }
        if (_jspx_th_spring_005fescapeBody_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fescapeBody_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fescapeBody_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fescapeBody_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fescapeBody_0026_005fjavaScriptEscape.reuse(_jspx_th_spring_005fescapeBody_005f5);
      _jspx_th_spring_005fescapeBody_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fescapeBody_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005fescapeBody_005f5_reused);
    }
    return false;
  }
}
